Feature/34463 order state management
shoppingflux/module-prestashop pull request #152
Opened 2022-05-12 09:51 UTC by bogdan202

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes #{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2022-06-10 09:34 UTC, clotairer requested changes

2022-06-10 15:33 UTC, bogdan202 commented on src/OrderImport/SFOrderState.php
> +    const SF_ORDER_STATE = 'SHOPPINGFEED_ORDER_STATE';
done

2022-06-10 15:38 UTC, bogdan202 commented on classes/actions/ShoppingfeedOrderImportActions.php
> +                $this->initSfOrderState()->get()->id,
SFOrderState::get() returns SHOPPINGFEED_ORDER_STATE
if it doesn't exist, then SFOrderState creates it
if creating is failed, then it returns PS_OS_PAYMENT

2022-06-10 16:08 UTC, clotairer commented on classes/actions/ShoppingfeedOrderImportActions.php
> +                $this->initSfOrderState()->get()->id,
the problem is that if a merchant upgrade the module, new order trigger the SHOPPINGFEED_ORDER_STATE state and new order will be imported in this new state. But if he an ERP that use PS_OS_PAYMENT to sync new order, he need to change the configuration somewhere. We don't supply a continuous behaviour and introduce a BC.

2022-06-12 16:37 UTC, clotairer requested changes

2022-06-15 08:03 UTC, bogdan202 commented on classes/actions/ShoppingfeedOrderImportActions.php
> +                $this->initSfOrderState()->get()->id,
Added the possibility to configure the first order state after an import

2022-06-15 17:19 UTC, clotairer requested changes

2022-06-16 09:31 UTC, clotairer approved these changes

2022-06-16 09:33 UTC, merged