Feature/34374 colissimo rule
shoppingflux/module-prestashop pull request #153
Opened 2022-05-12 12:36 UTC by bogdan202

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes #{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2022-06-10 12:23 UTC, clotairer requested changes

2022-06-10 14:54 UTC, bogdan202 commented on 202/tests/OrderImport/OrderImportSimpleTest.php
> +    public function addDpdCarrierAssociation()
I moved the tests to the file OrderImportManoManoDpdRelaisWithDoubleTaxOnProductTest.php
The logic was divided into the customer checking, the order details checking, the carrier checking

2022-06-10 14:54 UTC, bogdan202 commented on 202/tests/OrderImport/OrderImportSimpleTest.php
> +
done

2022-06-10 16:27 UTC, clotairer commented on 202/tests/OrderImport/OrderImportSimpleTest.php
> +    public function addDpdCarrierAssociation()
Thank you. I think it's a good refactoring.

2022-06-10 16:28 UTC, clotairer approved these changes

2022-06-15 17:23 UTC, clotairer approved these changes

2022-06-16 08:20 UTC, merged