refs #38070 - add ecotax in product variation attributes
shoppingflux/module-prestashop pull request #238
Opened 2022-12-27 10:45 UTC by yves202

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | add ecotax in product variation attributes.
| Type?         | improvement
| BC breaks?    |no
| Deprecations? |no
| Fixed ticket? | Fixes #38070
| How to test?  |

2022-12-28 17:28 UTC, clotairer commented
il faudrait nettoyer l’ancienne PR. 
Par exemple : ligne 111
[src/Services/ProductAttributeCombination.php](https://github.com/shoppingflux/module-prestashop/blob/23dc194d3fdf49de35bb7173ef9412037a82b074/src/Services/ProductAttributeCombination.php)

2023-01-02 10:38 UTC, clotairer requested changes

2023-01-02 10:38 UTC, clotairer commented on src/Services/ProductAttributeCombination.php
> -                $combinations[$idProductAttribute]['ecotax'] = $row['ecotax'];
Si tu le supprimes ici, tu vas pas le retrouver dans ProductSerializer.php, non ?

2023-01-02 10:41 UTC, yves202 commented on src/Services/ProductAttributeCombination.php
> -                $combinations[$idProductAttribute]['ecotax'] = $row['ecotax'];
on le retroluvera jamais, la pull request est pas accepter,
https://github.com/shoppingflux/module-prestashop/blob/develop/controllers/front/product.php#L170

2023-01-02 10:58 UTC, clotairer requested changes

2023-01-02 10:58 UTC, clotairer commented on src/Services/ProductSerializer.php
> +                $variation['attributes']['ecotax_child'] = $combination['ecotax'];
possible de couvrir pa run test unitaire ?

2023-01-03 21:14 UTC, clotairer approved these changes

2023-01-06 13:42 UTC, clotairer approved these changes

2023-02-20 16:02 UTC, merged